apiVersion: v1
kind: Pod
metadata:
  name: auth-db-deployment
  labels:
    app: auth-db
# spec:
#   selector:
#     matchLabels:
#       app: auth-db
  # template:
  #   metadata:
  #     labels:
  #       app: auth-db
spec:
  containers:
  - name: auth-db 
    image: maliksblr92/auth-db:latest
    ports: 
    - containerPort: 27017
