apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0
spec:
  # replicas: 2
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name:  kafka
        image: wurstmeister/kafka
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          # value: "30718"
          value: "31517"

        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-broker0
          # valueFrom:
          #         fieldRef:
          #           fieldPath: metadata.name

        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181

        - name: KAFKA_BROKER_ID
          value: "0"

        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1

