
# https://www.magalix.com/blog/kafka-on-kubernetes-and-deploying-best-practice
apiVersion: v1
kind: Pod
metadata:
  name: kafka-broker-deployment
  labels:
    app: kafka-broker
    id: "0"
spec:
  # selector:
  #   matchLabels:
  #     app: kafka-broker
  #     id: "0"
  # template:
  #   metadata:
  #     labels:
  #       app: kafka-broker
  #       id: "0"
spec:
  containers:
  - name: kafka-broker 
    image:  wurstmeister/kafka 
    ports: 
    - containerPort: 9092
    env:
    - name: KAFKA_ADVERTISED_PORT
      value: "30718" 
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: 192.168.1.240
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper1:2181
    - name: KAFKA_BROKER_ID
      value: "0"
    - name: KAFKA_CREATE_TOPICS
      value: admintome-test:1:1
