apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
spec:
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app:  zookeeper-1
    spec:
      containers:
      - name:  zookeeper-1
        image: digitalwonderland/zookeeper
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"

        - name: ZOOKEEPER_SERVER_1
          value: "1"


