
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
    id: "0"
# spec:
#   selector:
#     matchLabels:
#       app: zookeeper
#       id: "0"
#   template:
#     metadata:
#       labels:
#         app: zookeeper
#         id: "0"
spec:
  containers:
  - name: zookeeper1 
    image:  digitalwonderland/zookeeper
    ports: 
    - containerPort: 2181
    env:
    - name: ZOOKEEPER_ID
      value: "1" 
    - name: ZOOKEEPER_SERVER_1
      value: zookeeper1
