version: "3.4"
services:
  auth-microservice:
    # build:
    #   context: ./auth-microservice
    #   dockerfile: Dockerfile.development
    # container_name: auth-microservice
    image: maliksblr92/auth-microservice:latest
    ports:
      - 3001:3001
    restart: always
    volumes:
      - ./auth-microservice:/var/www/burency/auth-microservice
    env_file:
      - ./auth-microservice/.env.development
    networks:
      - proxyNetwork


  auth-db:
    image: maliksblr92/auth-db:latest
    container_name: auth-db
    restart: always
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: auth-db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./data/auth-db:/data/db
    ports:
      - "27017:27017"
    networks:
      - proxyNetwork

volumes:
  auth-microservice:
    driver: local
  auth-db:
    driver: local

networks:
  proxyNetwork:
    name: custom_network