apiVersion: v1
kind: Service
metadata:
  name: auth-microservice-service
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3001
      nodePort: 31516
  selector:
    app: auth-microservice

