apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  labels:
    name: auth-db
spec:
  selector:
      app: auth-db
  type: NodePort
  ports:
    - port: 27018
      targetPort: 27017
      nodePort: 31515

