
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  type: NodePort
  ports:
    - port: 3051
      targetPort: 9092
      nodePort: 31517
  selector:
    app: kafka
    # id: "0"










