
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  type: NodePort
  ports:
    - port: 3051
      targetPort: 9092
      nodePort: 30718
  selector:
    app: kafka
    id: "0"










