apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper
spec:
  selector:
      app: zookeeper
      id: "0"
  type: NodePort
  ports:
    - name: client
      port: 3052
      targetPort: 2181
      nodePort: 31519

    - name: follower
      port: 3053
      targetPort: 2888
      nodePort: 31520

    - name: leader
      port: 3054
      targetPort: 3888
      nodePort: 31521

