apiVersion: v1
kind: Pod
metadata:
  name: auth-db-deployment
  labels:
    app: auth-db
spec:
  containers:
  - name: auth-db 
    image: maliksblr92/auth-db:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports: 
    - containerPort: 27017





# spec:
#   selector:
#     matchLabels:
#       app: auth-db
  # template:
  #   metadata:
  #     labels:
  #       app: auth-db