apiVersion: v1
kind: Pod
metadata:
  name: auth-microservice-deployment
  labels:
    app: auth-microservice
spec:
  containers:
  - name: auth-microservice 
    image: maliksblr92/auth-microservice:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports: 
    - containerPort: 3001
