
# https://www.magalix.com/blog/kafka-on-kubernetes-and-deploying-best-practice


apiVersion: v1
kind: Pod
metadata:
  name: kafka-deployment
  labels:
    app: kafka
    id: "0"
spec:
  containers:
  - name: kafka 
    image:  wurstmeister/kafka 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports: 
    - containerPort: 9092
    env:
    - name: KAFKA_ADVERTISED_PORT
      # value: "30718"
      value: "30718"
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: 192.168.49.2
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper-service:3052
    - name: KAFKA_BROKER_ID
      value: "0"
    - name: KAFKA_CREATE_TOPICS
      value: admintome-test:1:1
